name: Mulesoft
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
      configurations-token:
        required: true
        description: Access token to get the configuration for the service

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      #For testing dynamic content
      MavenCompile: mvn compile

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Get the source code
        uses: actions/checkout@v3

      - name: Azure log-in
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Azure get KeyVault secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
          secrets: '
            salesforce-principal,
            salesforce-consumerkey,
            salesforce-keystore,
            salesforce-storepassword,
            mulesoft-nexus-ee-user,
            mulesoft-nexus-ee-password,
            cicd-connectedapp-clientid,
            cicd-connectedapp-secret
            '
        id: secretmanager # ID for secrets that you will reference
      
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
                  
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          #check-latest: true
          cache: 'maven'

      # Creates a settings.xml file and configure the anypoint repositories for the organization and the mulesoft EE
      - name: Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: >
            [
              {
                "id": "anypoint-exchange-v3",
                "username": "~~~Client~~~",
                "password": "${{ steps.secretmanager.outputs.cicd-connectedapp-clientid }}~?~${{ steps.secretmanager.outputs.cicd-connectedapp-secret }}" 
              },
              {
                "id": "mulesoft-enterprise-repository",
                "username": "${{ steps.secretmanager.outputs.mulesoft-nexus-ee-user }}",
                "password": "${{ steps.secretmanager.outputs.mulesoft-nexus-ee-password }}" 
              }
            ]
          repositories: >
            [
              {
                "id": "anypoint-exchange-v3",
                "name": "Assets for your anypoint organization",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven/"
              },
              {
                "id": "mulesoft-releases",
                "name": "mulesoft-releases",
                "url": "https://repository-master.mulesoft.org/releases/"
              },
              {
                "id": "mulesoft-snapshots",
                "name": "MuleSoft Snapshot Repository",
                "url": "https://repository-master.mulesoft.org/snapshots/"
              },
              {
                "id": "mulesoft-enterprise-repository",
                "name": "MuleSoft Enterprise Repository",
                "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "mulesoft-plugins",
                "name": "Mulesoft plugins-release",
                "url": "https://repository.mulesoft.org/nexus/content/repositories/public/"
              },
              {
                "id": "central-plugins",
                "name": "plugins-release",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "mulesoft-snapshots",
                "name": "MuleSoft Snapshot Repository",
                "url": "https://repository-master.mulesoft.org/snapshots/"
              },
              {
                "id": "mulesoft-plugins-release",
                "name": "Mulesoft plugins-release",
                "url": "https://repository.mulesoft.org/releases/",
                "snapshots": {
                  "enabled": "false",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                }
              }              
            ]
        
      - name: DEBUG - Show settings file
        run: |
          ls -la $HOME
          cat $HOME/.m2/settings.xml
          echo ${{ github.run_number }}

      - name: Copy Anypoint Exchange documentation
        run: |
          cp -Rfpv README.md exchange-docs/home.md
          cp -Rfpv docs/*.* exchange-docs/docs/*.* 

      - name: Compile code
        # I am using an environment variable just for testing dinamic content execution
        run: $MavenCompile

      - name: Run test cases and package
        run: |
          ## Get the git commit hash 
          commitHash=$(git rev-parse --short "$GITHUB_SHA")

          mvn package -DskipTests \
           -Dsalesforce.principal="${{ steps.secretmanager.outputs.salesforce-principal }}" \
           -Dsalesforce.consumerkey="${{ steps.secretmanager.outputs.salesforce-consumerkey }}" \
           -Dsalesforce.keystore="${{ steps.secretmanager.outputs.salesforce-keystore }}" \
           -Dsalesforce.storepassword="${{ steps.secretmanager.outputs.salesforce-storepassword }}"

      - name: Deploy to anypoint exchange
        if: ${{ false }}    
        run: |
          ## Deploy to anypoint exchange
          mvn deploy -DskipTests 

      - name: Publish - MUnit Application Coverage Report
        uses: actions/upload-artifact@master
        with:
          name: munit-application-coverage-report
          path: target/site/munit/coverage/*
      
      - name: Publish - MUnit Report
        uses: actions/upload-artifact@master
        with:
          name: munit-test-report
          path: target/surefire-reports/*

      - name: Publish - JAR 
        uses: actions/upload-artifact@master
        with:
          name: jar
          path: target/*.jar

      - name: Publish - POM 
        uses: actions/upload-artifact@master
        with:
          name: pom
          path: pom.xml

  build-backup:
    name: Build 
    if: ${{ false }}    
    runs-on: ubuntu-latest
    env:
      MavenCompile: mvn compile

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Get the source code
        uses: actions/checkout@v3

      - name: DEBUG - echo
        run: |
          echo "HOME:"
          ls -la $HOME
          echo "tree HOME/work"
          tree $HOME/work
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Run number: ${{ github.run_number }}"










  deploy-dev:
    name: Development
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'https://dev.myapp.com'
    steps:
      - name: Get JAR file
        uses: actions/download-artifact@v2
        with:
          name: jar

      - name: Get POM file
        uses: actions/download-artifact@v2
        with:
          name: pom

      - name: DEBUG - Print directory tree and variables
        run: |
          echo "HOME:"
          ls -la $HOME
          #echo "tree HOME/work"
          #tree $HOME/work
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Run number: ${{ github.run_number }}"

      - name: Azure log-in
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Azure get KeyVault secrets
        uses: Azure/get-keyvault-secrets@v1.1
        with:
          keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
          secrets: '
                    cicd-connectedapp-clientid,
                    cicd-connectedapp-secret,
                    salesforce-principal,
                    salesforce-consumerkey,
                    salesforce-keystore,
                    salesforce-storepassword
                    '
        id: secretmanager # ID for secrets that you will reference

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Anypoint CLI
        run: |
          echo "Install anypoint-cli-v4..."
          npm install -g anypoint-cli-v4
          echo ""
          echo "anypoint-cli-v4 --version: "
          anypoint-cli-v4 --version
          echo ""
          echo "Installing cloudhub-plugin"
          anypoint-cli-v4 plugins:install anypoint-cli-cloudhub-plugin

      - name: Deploy Application
        run: |
          ANYPOINT_CLIENT_ID="${{ steps.secretmanager.outputs.cicd-connectedapp-clientid }}"
          ANYPOINT_CLIENT_SECRET="${{ steps.secretmanager.outputs.cicd-connectedapp-secret }}"
          configurationtoken=${{ secrets.configurations-token }}

          #POM and JAR file must be in the root directory
          echo "Getting the service metadata from pom file for deployment"
          service=$(sed -n 's:.*<name>\(.*\)</name>.*:\1:p' pom.xml | sed -n 1p)
          servicegroup=$(sed -n 's:.*<groupId>\(.*\)</groupId>.*:\1:p' pom.xml | sed -n 2p)
          serviceartifact=$(sed -n 's:.*<artifactId>\(.*\)</artifactId>.*:\1:p' pom.xml | sed -n 2p)
          serviceversion=$(sed -n 's:.*<version>\(.*\)</version>.*:\1:p' pom.xml | sed -n 2p)
          
          # Get the jar file
          jar=$(ls *.jar)
          echo "Jar file: $jar"

          # Show variables for the script
          echo "Service name: $service"
          echo "Service group: $servicegroup"
          echo "Service artifact: $serviceartifact"
          echo "Service version: $serviceversion"
          envsuffix="-dev"
          deploymentname=$service$envsuffix
          echo "Deployment name: $deploymentname"
          echo "Jar file: $jar"

          # Get the configuration file for the service
          configurationfile=$deploymentname.yml
          urlconfigurationfile="https://raw.githubusercontent.com/jpontdia/mule-configurations/main/$configurationfile"
          echo "Getting the configuration file: $urlconfigurationfile"
          configurationdata=$(curl -sH "Authorization: token $configurationtoken" $urlconfigurationfile)
          confcloudhub=$(echo $configurationfile | jq -r ".cloudhub")
          confproperties=$(echo $configurationfile | jq -r ".properties")
          echo $confcloudhub
          echo $confproperties
          start=$(date +%s)
          echo ""
          echo "Deployment process start"

          # Get the current status of the service
          STATUS=$(\
            anypoint-cli-v4 runtime-mgr cloudhub-application describe \
            --client_id $ANYPOINT_CLIENT_ID \
            --client_secret $ANYPOINT_CLIENT_SECRET \
            --output "json" $deploymentname | jq -r ".status")
          echo "Deployment status for service: $deploymentname is: $STATUS"

          # Verify if deployment is for update or new application
          operation="deploy"
          if [ "$STATUS" != "" ]; then
            operation="modify"
          fi

          echo ""
          echo "Deployment operation for serivce: $deploymentname is: $operation"
          end=$(date +%s)
          echo "  Elapsed time: $(($end-$start)) seconds"
          echo "Deploying...."
          anypoint-cli-v4 runtime-mgr cloudhub-application $operation \
          --client_id $ANYPOINT_CLIENT_ID \
          --client_secret $ANYPOINT_CLIENT_SECRET \
          --runtime "4.4.0" \
          --region "us-west-1" \
          --workers "1" \
          --workerSize "0.1" \
          --property "salesforce.storepassword:micorpintegration" \
          --property "salesforce.principal:micorp.integration@yopmail.com" \
          --property "salesforce.consumerkey:3MVG99gP.VbJma8Wlu2C246aMscxqW6uf16qBTqgJ_W_83zcxkOHabPMNVQ7Zp9w9erow6j2.ANtwFErPBHS3" \
          --property "salesforce.keystore:keystore.jks" \
          --property "logzio.token:MKMjnTtiZSElNvyOokkGBnnMFlcOQift" \
          --property "logzio.url:https\://listener.logz.io\:8071" \
          --property "otel.collectorendpoint:http\://13.52.179.177\:4317" \
          --property "otel.servicename:micorp-customer-sapi-dev" \
          --property "api.id:17868760" \
          --property "env:dev" \
          --property "anypoint.platform.client_id:1fd4a0841a6a47eba4cb2934ca1baf32" \
          --property "anypoint.platform.client_secret:F77CfFEA3a9741A19B2905173F910134" \
          --property "anypoint.platform.config.analytics.agent.enabled:true" \
          --output "json" "$deploymentname" "$jar"

          end=$(date +%s)
          echo ""
          echo "Deployment finished, verifying the deployment...."
          echo "  Elapsed time: $(($end-$start)) seconds" 

          iteration=1
          limit=60
          while true
          do 
            sleep 5

            # Get the current status of the service
            DEPLOYMENT_INFO=$(\
              anypoint-cli-v4 runtime-mgr cloudhub-application describe \
              --client_id $ANYPOINT_CLIENT_ID \
              --client_secret $ANYPOINT_CLIENT_SECRET \
              --output "json" $deploymentname)
            STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".status")
            UPDATE_STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".deploymentUpdateStatus")  
            echo "Service: $deploymentname status: $STATUS, updateStatus: $UPDATE_STATUS"

            end=$(date +%s)
            echo "  Elapsed time: $(($end-$start)) seconds, iteration: $iteration limit: $limit"

            if [ "$operation" = "deploy" ]; then
                # Create service

                if [ "$STATUS" = "STARTED" ] || [ $iteration -eq $limit ]; then
                  break # Abandon the while loop.
                fi
            else
                # Update service
                if [ "$UPDATE_STATUS" = "null" ] || [ $iteration -eq $limit ]; then
                  break # Abandon the while loop.
                fi
            fi

            iteration=$(( $iteration + 1 ))
          done

          if [ "$STATUS" != "STARTED" ]; then
            echo "Error: The service was not deployed in the expected time, review logs"
            echo "  example: anypoint-cli-v4 runtime-mgr cloudhub-application download-logs {APP-NAME}"
            echo "The expected iterations were 44 but the proccess reached the limit: $limit"

            exit 1 # terminate and indicate error
          else
            echo "Deployment successful.."
          fi